# Generated by Django 3.2.9 on 2022-01-06 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_auto_20220106_1041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'permissions': (('setar_nfe', 'Usuário pode alterar o parametro nfe'), ('ver_dashboard', 'Pode Visualizar o dashboard'), ('permissao2', 'permissao2'))},
        ),
    ]
