# Generated by Django 3.2.9 on 2022-01-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_auto_20220105_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='nfe_emitida',
            field=models.BooleanField(default=False),
        ),
    ]
