# Generated by Django 3.2.9 on 2022-01-05 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_alter_venda_nfe_emitida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='pessoa',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='produtos',
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
        migrations.DeleteModel(
            name='Venda',
        ),
    ]
